# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/zricethezav/gitleaks
    rev: v7.5.0
    hooks:
    -   id: gitleaks
